// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hlmZm-2P9D7obuHXtwbry7uk1igTo_s',
    appId: '1:657505869729:android:a1847e17098842c3c875e0',
    messagingSenderId: '657505869729',
    projectId: 'chat-app-95642',
    storageBucket: 'chat-app-95642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLQLbhautWvb1ozUrCcAomLscreSH_44',
    appId: '1:657505869729:ios:2858515fe238601ec875e0',
    messagingSenderId: '657505869729',
    projectId: 'chat-app-95642',
    storageBucket: 'chat-app-95642.appspot.com',
    androidClientId: '657505869729-8s72lr9bki9ojjaau7rr5qa4df7rpk8h.apps.googleusercontent.com',
    iosClientId: '657505869729-10ovk46v7p8ue5jq16s5skg6vh963cru.apps.googleusercontent.com',
    iosBundleId: 'com.punam.chatApp',
  );
}
